pipeline{
    agent any

    stages{
        stage('Hello'){
            steps{
                sh'echo "Hello guys"'
            }
        }
        stage('How'){
            steps{
                sh'echo "How are you?"'
            }
        }
    }
}