pipeline{
    agent { label 'Dev' }

    stages{
        stage('Hello'){
            steps{
                sh'echo "Hello guys"'
            }
        }
        stage('How'){
            steps{
                sh'echo "How are you?"'
            }
        }
        stage('where'){
            steps{
                sh'echo "Where are you"'
            }
        }
    }
}
